<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro"    
 	xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor" 
    xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller" 
    xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface" 
    name="myBicycle">
    <xacro:property name="body_x" value="4" />
    <xacro:property name="body_y" value="4" />
    <xacro:property name="body_z" value="2" />

    <link name="base_link">
        <visual>
            <geometry>
                <box size="${body_x} ${body_y} ${body_z}" />
            </geometry>
            <origin rpy="0 0 0 " xyz="0 0 ${body_z/2}"/> 
            <material name="black"/>
        </visual>   
    </link>

    <link name="head">
        <visual>
            <geometry>
                <box size="${body_x-0.1} ${body_y} ${body_z}" />
            </geometry>
            <origin rpy="0 0 0 " xyz="0 0 ${body_z/2}"/>
            <material name="red">
                <color rgba="1.0 0 0 1.0"/>
            </material>
        </visual>   
    </link>

    <joint name="base_to_head" type="fixed">
        <parent link="base_link"/>
        <child link="head"/>
        <origin xyz="${body_x/2+(body_x-0.1)/2} 0  0" rpy="0 0 0"/>
    </joint>
</robot>